log:
  level: "info"

# slurm 数据库配置
mysql:
  host: 127.0.0.1
  port: 3306
  user: root
  dbname: slurm_acct_db
  password: 81SLURM@@rabGTjN7
  clustername: cluster
  databaseencode: latin1

# 服务地址设置
service:
  addr: 0.0.0.0:8972

# slurm 默认Qos设置
slurm:
  defaultqos: normal

# module profile文件路径
modulepath:
  path: /lustre/software/module/5.2.0/init/profile.sh

# 计算分区描述
partitiondesc:
  - name: compute      # 这个是计算分区名
    desc: "这是普通的cpu计算分区"  # 这是描述
